<#
.SYNOPSIS
    ExportService module for Active Directory Management Studio.
.DESCRIPTION
    Provides CSV/Excel-compatible export capabilities with proper encoding, delimiter selection,
    and column mapping.
#>

function Export-ADDataToCsv {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [System.Collections.IEnumerable]$Data,

        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [string]$Delimiter = ";",

        [string[]]$PropertiesToExport = @()
    )

    try {
        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $exportList = if ($PropertiesToExport -and $PropertiesToExport.Count -gt 0) {
            $Data | Select-Object -Property $PropertiesToExport
        } else {
            $Data
        }

        # Export with UTF-8 encoding and specified delimiter
        $exportList | Export-Csv -Path $FilePath -Delimiter $Delimiter -NoTypeInformation -Encoding UTF8

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = @($exportList).Count
            Message  = "Export completed successfully ($(@($exportList).Count) records)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "Export failed: $_"
        }
    }
}

function Export-ADDataToLdif {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [System.Collections.IEnumerable]$Data,

        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [string]$ChangeType = "" # e.g. "add", "modify"
    )

    try {
        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $sb = New-Object System.Text.StringBuilder
        [void]$sb.AppendLine("version: 1")
        [void]$sb.AppendLine("# Generated by Active Directory Management Studio (LDIF Engine)")
        [void]$sb.AppendLine("# Export Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
        [void]$sb.AppendLine("")

        $count = 0
        foreach ($item in $Data) {
            $dn = $item.DistinguishedName
            if (-not $dn -and $item.PSObject.Properties['DN']) { $dn = $item.DN }
            if (-not $dn -and $item.PSObject.Properties['distinguishedName']) { $dn = $item.distinguishedName }
            if (-not $dn) { continue }

            [void]$sb.AppendLine("dn: $dn")
            if ($ChangeType) {
                [void]$sb.AppendLine("changetype: $ChangeType")
            }

            foreach ($prop in $item.PSObject.Properties) {
                $name = $prop.Name
                $val = $prop.Value
                if ($name -match '^(DistinguishedName|DN|distinguishedName|RawValue|FlagList)$' -or $null -eq $val) {
                    continue
                }

                if ($val -is [System.Collections.IEnumerable] -and $val -isnot [string]) {
                    foreach ($subVal in $val) {
                        if ($subVal) { [void]$sb.AppendLine("${name}: $subVal") }
                    }
                }
                else {
                    $strVal = $val.ToString()
                    if ($strVal) { [void]$sb.AppendLine("${name}: $strVal") }
                }
            }

            [void]$sb.AppendLine("")
            $count++
        }

        [System.IO.File]::WriteAllText($FilePath, $sb.ToString(), [System.Text.Encoding]::UTF8)

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = $count
            Message  = "LDIF export completed successfully ($count entries)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "LDIF export failed: $_"
        }
    }
}

function Export-ADDataToJson {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [System.Collections.IEnumerable]$Data,

        [Parameter(Mandatory = $true)]
        [string]$FilePath
    )

    try {
        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $json = $Data | ConvertTo-Json -Depth 5
        [System.IO.File]::WriteAllText($FilePath, $json, [System.Text.Encoding]::UTF8)

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = @($Data).Count
            Message  = "JSON export completed successfully ($(@($Data).Count) records)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "JSON export failed: $_"
        }
    }
}

function Export-ADSecurityAuditToHtml {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $false)]
        $AuditReport = $null,

        [Parameter(Mandatory = $false)]
        [string]$ReportTitle = "",

        [Parameter(Mandatory = $false)]
        [hashtable]$SummaryStats = @{},

        [Parameter(Mandatory = $false)]
        [System.Collections.IEnumerable]$Data = @(),

        [Parameter(Mandatory = $true)]
        [string]$FilePath
    )

    try {
        if ($AuditReport) {
            if (-not $ReportTitle) {
                $ReportTitle = if ($AuditReport.Title) { $AuditReport.Title } else { "Active Directory Security Audit Report" }
            }
            if ($AuditReport.SummaryStats -and -not $SummaryStats.Count) {
                $SummaryStats = [hashtable]$AuditReport.SummaryStats
            } elseif (-not $SummaryStats.Count) {
                $SummaryStats = [ordered]@{ "Total Findings" = $AuditReport.Count; "Category" = $AuditReport.Category }
            }
            if (-not $Data -or $Data.Count -eq 0) {
                $Data = if ($AuditReport.Findings) { $AuditReport.Findings } else { $AuditReport.Results }
            }
        }

        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

        $cardsHtml = ""
        foreach ($k in $SummaryStats.Keys) {
            $val = $SummaryStats[$k]
            $cardsHtml += @"
            <div class="card">
                <div class="card-val">$val</div>
                <div class="card-label">$k</div>
            </div>
"@
        }

        # Convert data items to HTML table rows
        $first = $Data | Select-Object -First 1
        $headers = if ($first) { $first.PSObject.Properties.Name } else { @() }
        
        $thHtml = ($headers | ForEach-Object { "<th>$_</th>" }) -join ""
        $trHtml = ""

        foreach ($row in $Data) {
            $tds = foreach ($h in $headers) {
                $v = $row.$h
                "<td>$([System.Net.WebUtility]::HtmlEncode("$v"))</td>"
            }
            $trHtml += "<tr>$($tds -join '')</tr>`n"
        }

        $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>$ReportTitle - Active Directory Management Studio</title>
<style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0F1117; color: #E1E7EF; margin: 0; padding: 24px; }
    .header { border-bottom: 2px solid #2A2E3D; padding-bottom: 16px; margin-bottom: 24px; }
    .title { font-size: 24px; font-weight: bold; color: #60A5FA; margin: 0 0 6px 0; }
    .meta { font-size: 13px; color: #94A3B8; }
    .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 28px; }
    .card { background: #1A1D27; border: 1px solid #2D3345; border-radius: 8px; padding: 16px; text-align: center; }
    .card-val { font-size: 28px; font-weight: bold; color: #38BDF8; }
    .card-label { font-size: 12px; color: #94A3B8; text-transform: uppercase; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; background: #161821; border-radius: 8px; overflow: hidden; border: 1px solid #2A2E3D; }
    th { background: #1E2230; color: #F1F5F9; font-weight: 600; text-align: left; padding: 12px 14px; font-size: 13px; border-bottom: 1px solid #2A2E3D; }
    td { padding: 10px 14px; border-bottom: 1px solid #232736; font-size: 13px; color: #CBD5E1; }
    tr:hover { background: #1C202C; }
    .footer { margin-top: 28px; font-size: 12px; color: #64748B; text-align: center; }
</style>
</head>
<body>
    <div class="header">
        <div class="title">&#x1F6E1;&#xFE0F; $ReportTitle</div>
        <div class="meta">Generated: $now | Source: Active Directory Management Studio</div>
    </div>

    <div class="cards">
        $cardsHtml
    </div>

    <table>
        <thead>
            <tr>$thHtml</tr>
        </thead>
        <tbody>
            $trHtml
        </tbody>
    </table>

    <div class="footer">
        Active Directory Management Studio &bull; Enterprise Directory Services & Audit Suite
    </div>
</body>
</html>
"@

        [System.IO.File]::WriteAllText($FilePath, $html, [System.Text.Encoding]::UTF8)

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = @($Data).Count
            Message  = "HTML Report generated successfully ($(@($Data).Count) records)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "HTML Report generation failed: $_"
        }
    }
}

function Get-ADObjectHtmlContent {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        $ObjectDetail,

        [Parameter(Mandatory = $false)]
        [System.Collections.IEnumerable]$Attributes = @(),

        [Parameter(Mandatory = $false)]
        [ValidateSet("Dark", "Light")]
        [string]$Theme = "Dark",

        [Parameter(Mandatory = $false)]
        [ValidateSet("Technical", "Executive", "Groups", "Raw")]
        [string]$Template = "Technical",

        [Parameter(Mandatory = $false)]
        [string]$Title = ""
    )

    # Resolve primary attributes
    $dn = ""
    $sam = ""
    $upn = ""
    $dispName = ""
    $objClass = "user"
    $status = "Active"
    $mail = ""
    $title = ""
    $dept = ""
    $office = ""
    $company = ""
    $phone = ""
    $mobile = ""
    $manager = ""
    $created = ""
    $changed = ""
    $pwdLastSet = ""
    $acctExpires = ""
    $badPwdCount = ""
    $lastLogon = ""
    $guid = ""
    $sid = ""
    $groups = @()

    if ($ObjectDetail -is [System.Collections.IDictionary] -or $ObjectDetail.PSObject) {
        if ($ObjectDetail.DistinguishedName) { $dn = "$($ObjectDetail.DistinguishedName)" }
        elseif ($ObjectDetail.DN) { $dn = "$($ObjectDetail.DN)" }

        if ($ObjectDetail.SamAccountName) { $sam = "$($ObjectDetail.SamAccountName)" }
        if ($ObjectDetail.UserPrincipalName) { $upn = "$($ObjectDetail.UserPrincipalName)" }
        if ($ObjectDetail.DisplayName) { $dispName = "$($ObjectDetail.DisplayName)" }
        if ($ObjectDetail.ObjectClass) { $objClass = "$($ObjectDetail.ObjectClass)" }
        if ($ObjectDetail.Status) { $status = "$($ObjectDetail.Status)" }
        if ($ObjectDetail.Mail) { $mail = "$($ObjectDetail.Mail)" }
        if ($ObjectDetail.Title) { $title = "$($ObjectDetail.Title)" }
        if ($ObjectDetail.Department) { $dept = "$($ObjectDetail.Department)" }
        if ($ObjectDetail.Office) { $office = "$($ObjectDetail.Office)" }
        if ($ObjectDetail.Company) { $company = "$($ObjectDetail.Company)" }
        if ($ObjectDetail.TelephoneNumber) { $phone = "$($ObjectDetail.TelephoneNumber)" }
        if ($ObjectDetail.Mobile) { $mobile = "$($ObjectDetail.Mobile)" }
        if ($ObjectDetail.Manager) { $manager = "$($ObjectDetail.Manager)" }
        if ($ObjectDetail.WhenCreated) { $created = "$($ObjectDetail.WhenCreated)" }
        if ($ObjectDetail.WhenChanged) { $changed = "$($ObjectDetail.WhenChanged)" }
        if ($ObjectDetail.PasswordLastSet) { $pwdLastSet = "$($ObjectDetail.PasswordLastSet)" }
        if ($ObjectDetail.AccountExpirationDate) { $acctExpires = "$($ObjectDetail.AccountExpirationDate)" }
        if ($ObjectDetail.BadPwdCount) { $badPwdCount = "$($ObjectDetail.BadPwdCount)" }
        if ($ObjectDetail.LastLogon) { $lastLogon = "$($ObjectDetail.LastLogon)" }
        if ($ObjectDetail.ObjectGUID) { $guid = "$($ObjectDetail.ObjectGUID)" }
        if ($ObjectDetail.SID) { $sid = "$($ObjectDetail.SID)" }
        if ($ObjectDetail.MemberOf) { $groups = @($ObjectDetail.MemberOf) }
    }

    # Fallback from attributes list if fields are blank
    if ($Attributes -and $Attributes.Count -gt 0) {
        foreach ($attr in $Attributes) {
            $n = $attr.Name
            $v = "$($attr.Value)"
            if (-not $dn -and $n -ieq 'distinguishedName') { $dn = $v }
            if (-not $sam -and $n -ieq 'sAMAccountName') { $sam = $v }
            if (-not $upn -and $n -ieq 'userPrincipalName') { $upn = $v }
            if (-not $dispName -and $n -ieq 'displayName') { $dispName = $v }
            if (-not $mail -and $n -ieq 'mail') { $mail = $v }
            if (-not $title -and $n -ieq 'title') { $title = $v }
            if (-not $dept -and $n -ieq 'department') { $dept = $v }
            if (-not $office -and $n -ieq 'physicalDeliveryOfficeName') { $office = $v }
            if (-not $company -and $n -ieq 'company') { $company = $v }
            if (-not $phone -and $n -ieq 'telephoneNumber') { $phone = $v }
            if (-not $mobile -and $n -ieq 'mobile') { $mobile = $v }
            if (-not $manager -and $n -ieq 'manager') { $manager = $v }
            if (-not $created -and $n -ieq 'whenCreated') { $created = $v }
            if (-not $changed -and $n -ieq 'whenChanged') { $changed = $v }
            if (-not $pwdLastSet -and $n -ieq 'pwdLastSet') { $pwdLastSet = $v }
            if (-not $acctExpires -and $n -ieq 'accountExpires') { $acctExpires = $v }
            if (-not $badPwdCount -and $n -ieq 'badPwdCount') { $badPwdCount = $v }
            if (-not $lastLogon -and ($n -ieq 'lastLogonTimestamp' -or $n -ieq 'lastLogon')) { $lastLogon = $v }
            if (-not $guid -and $n -ieq 'objectGUID') { $guid = $v }
            if (-not $sid -and $n -ieq 'objectSid') { $sid = $v }
            if ($groups.Count -eq 0 -and $n -ieq 'memberOf') {
                $groups = $v -split ';\s*'
            }
        }
    }

    if (-not $dispName) { $dispName = if ($sam) { $sam } else { $dn } }
    if (-not $Title) { $Title = "Directory Dossier: $dispName" }
    $now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

    # Status badge color
    $statusColor = switch -Wildcard ($status) {
        "*Active*"   { "#10B981" }
        "*Enabled*"  { "#10B981" }
        "*Disabled*" { "#EF4444" }
        "*Locked*"   { "#F59E0B" }
        default      { "#3B82F6" }
    }

    # Avatar initials
    $initials = if ($dispName -match '^\s*([A-Za-z0-9])') { $matches[1].ToUpper() } else { "AD" }

    # Groups list HTML
    $groupsHtml = if ($groups.Count -gt 0) {
        ($groups | ForEach-Object {
            $grpName = if ($_ -match '^CN=([^,]+)') { $matches[1] } else { $_ }
            "<span class='badge group-badge'>$([System.Net.WebUtility]::HtmlEncode($grpName))</span>"
        }) -join " "
    } else {
        "<span style='color:var(--text-muted); font-style:italic;'>No group memberships recorded or domain primary group only.</span>"
    }

    # Attributes Table HTML
    $attrRowsHtml = ""
    if ($Attributes -and $Attributes.Count -gt 0) {
        foreach ($attr in $Attributes) {
            $an = [System.Net.WebUtility]::HtmlEncode("$($attr.Name)")
            $av = [System.Net.WebUtility]::HtmlEncode("$($attr.Value)")
            $at = [System.Net.WebUtility]::HtmlEncode("$($attr.Type)")
            $opBadge = if ($attr.IsOperational) { "<span class='badge op-badge'>Op</span>" } else { "" }
            $attrRowsHtml += "<tr><td class='attr-name'><b>$an</b> $opBadge</td><td class='attr-val'>$av</td><td class='attr-type'>$at</td></tr>`n"
        }
    }

    $themeAttr = if ($Theme -ieq "Light") { "data-theme='light'" } else { "data-theme='dark'" }

    # Section rendering based on template
    $showIdentity = $Template -in @("Technical", "Executive", "Groups")
    $showOrg = $Template -in @("Technical", "Executive")
    $showTelemetry = $Template -eq "Technical"
    $showGroups = $Template -in @("Technical", "Executive", "Groups")
    $showAttributes = $Template -in @("Technical", "Raw")

    $cardsGridHtml = ""
    if ($showIdentity -or $showOrg -or $showTelemetry) {
        $cardsGridHtml += "<div class='cards-grid'>"
        if ($showIdentity) {
            $cardsGridHtml += @"
            <div class="panel-card">
                <h3>&#x1F194; Identity &amp; Naming</h3>
                <div class="field-row"><span class="field-label">Display Name:</span><span class="field-val">$([System.Net.WebUtility]::HtmlEncode($dispName))</span></div>
                <div class="field-row"><span class="field-label">Username (sAM):</span><span class="field-val">$([System.Net.WebUtility]::HtmlEncode($sam))</span></div>
                <div class="field-row"><span class="field-label">User Principal (UPN):</span><span class="field-val">$([System.Net.WebUtility]::HtmlEncode($upn))</span></div>
                <div class="field-row"><span class="field-label">Object Class:</span><span class="field-val">$objClass</span></div>
                <div class="field-row"><span class="field-label">Account Status:</span><span class="field-val" style="color: $statusColor;">$status</span></div>
                <div class="field-row"><span class="field-label">Distinguished Name:</span><span class="field-val" style="font-size:11px;">$([System.Net.WebUtility]::HtmlEncode($dn))</span></div>
                $(if ($guid) { "<div class='field-row'><span class='field-label'>Object GUID:</span><span class='field-val' style='font-size:11px;'>$guid</span></div>" })
                $(if ($sid) { "<div class='field-row'><span class='field-label'>Object SID:</span><span class='field-val' style='font-size:11px;'>$sid</span></div>" })
            </div>
"@
        }
        if ($showOrg) {
            $mailLink = if ($mail) { "<a href='mailto:$mail' style='color:var(--accent); text-decoration:none;'>$([System.Net.WebUtility]::HtmlEncode($mail))</a>" } else { "--" }
            $phoneLink = if ($phone) { "<a href='tel:$phone' style='color:var(--accent); text-decoration:none;'>$([System.Net.WebUtility]::HtmlEncode($phone))</a>" } else { "--" }
            $cardsGridHtml += @"
            <div class="panel-card">
                <h3>&#x1F4BC; Organization &amp; Contact</h3>
                <div class="field-row"><span class="field-label">Job Title:</span><span class="field-val">$([System.Net.WebUtility]::HtmlEncode($title))</span></div>
                <div class="field-row"><span class="field-label">Department:</span><span class="field-val">$([System.Net.WebUtility]::HtmlEncode($dept))</span></div>
                <div class="field-row"><span class="field-label">Company:</span><span class="field-val">$([System.Net.WebUtility]::HtmlEncode($company))</span></div>
                <div class="field-row"><span class="field-label">Office:</span><span class="field-val">$([System.Net.WebUtility]::HtmlEncode($office))</span></div>
                <div class="field-row"><span class="field-label">Email:</span><span class="field-val">$mailLink</span></div>
                <div class="field-row"><span class="field-label">Phone:</span><span class="field-val">$phoneLink</span></div>
                <div class="field-row"><span class="field-label">Mobile:</span><span class="field-val">$([System.Net.WebUtility]::HtmlEncode($mobile))</span></div>
                <div class="field-row"><span class="field-label">Manager:</span><span class="field-val" style="font-size:11px;">$([System.Net.WebUtility]::HtmlEncode($manager))</span></div>
            </div>
"@
        }
        if ($showTelemetry) {
            $cardsGridHtml += @"
            <div class="panel-card">
                <h3>&#x23F3; Lifecycle &amp; Security</h3>
                <div class="field-row"><span class="field-label">When Created:</span><span class="field-val">$created</span></div>
                <div class="field-row"><span class="field-label">When Changed:</span><span class="field-val">$changed</span></div>
                <div class="field-row"><span class="field-label">Password Last Set:</span><span class="field-val">$pwdLastSet</span></div>
                <div class="field-row"><span class="field-label">Account Expires:</span><span class="field-val">$acctExpires</span></div>
                <div class="field-row"><span class="field-label">Bad Password Count:</span><span class="field-val">$badPwdCount</span></div>
                <div class="field-row"><span class="field-label">Last Logon:</span><span class="field-val">$lastLogon</span></div>
            </div>
"@
        }
        $cardsGridHtml += "</div>"
    }

    $groupsBlockHtml = ""
    if ($showGroups) {
        $groupsBlockHtml = @"
        <div class="panel-card" style="margin-bottom: 24px;">
            <h3>&#x1F465; Direct Group Memberships ($($groups.Count))</h3>
            <div style="padding-top: 6px;">
                $groupsHtml
            </div>
        </div>
"@
    }

    $attrBlockHtml = ""
    if ($showAttributes -and $Attributes -and $Attributes.Count -gt 0) {
        $attrBlockHtml = @"
        <div class="section-title">&#x1F3F7;&#xFE0F; Complete Active Directory Attributes ($($Attributes.Count))</div>
        <table class="attr-table">
            <thead>
                <tr>
                    <th>Attribute Name</th>
                    <th>Decoded Value</th>
                    <th>Syntax / Type</th>
                </tr>
            </thead>
            <tbody>
                $attrRowsHtml
            </tbody>
        </table>
"@
    }

    $html = @"
<!DOCTYPE html>
<html lang="en" $themeAttr>
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title>$Title - Active Directory Management Studio</title>
<style>
    :root, [data-theme="dark"] {
        --bg-body: #0E1017;
        --bg-container: #141722;
        --bg-card: #161922;
        --bg-card-header: #1E2230;
        --bg-subtle: #111319;
        --border-color: #262B3D;
        --border-subtle: #1E2230;
        --text-primary: #F1F5F9;
        --text-secondary: #94A3B8;
        --text-muted: #64748B;
        --accent: #38BDF8;
        --accent-hover: #0284C7;
        --badge-bg: #1E293B;
        --badge-text: #93C5FD;
        --badge-border: #3B82F6;
        --table-row-hover: #1C202C;
    }
    [data-theme="light"] {
        --bg-body: #F8FAFC;
        --bg-container: #FFFFFF;
        --bg-card: #FFFFFF;
        --bg-card-header: #F1F5F9;
        --bg-subtle: #F8FAFC;
        --border-color: #CBD5E1;
        --border-subtle: #E2E8F0;
        --text-primary: #0F172A;
        --text-secondary: #475569;
        --text-muted: #64748B;
        --accent: #0284C7;
        --accent-hover: #0369A1;
        --badge-bg: #E0F2FE;
        --badge-text: #0369A1;
        --badge-border: #BAE6FD;
        --table-row-hover: #F1F5F9;
    }
    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
        background-color: var(--bg-body);
        color: var(--text-primary);
        margin: 0;
        padding: 20px;
    }
    .container { max-width: 1100px; margin: 0 auto; }
    .top-bar { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid var(--border-color); padding-bottom: 16px; margin-bottom: 24px; }
    .title-group { display: flex; align-items: center; }
    .avatar-circle { width: 44px; height: 44px; border-radius: 50%; background: var(--accent); color: #FFFFFF; display: flex; align-items: center; justify-content: center; font-size: 20px; font-weight: bold; margin-right: 14px; }
    .title-group h1 { margin: 0; font-size: 22px; color: var(--accent); }
    .title-group p { margin: 4px 0 0 0; font-size: 13px; color: var(--text-secondary); }
    .btn-bar { display: flex; align-items: center; }
    .btn-bar button { background: var(--accent); color: #FFFFFF; border: none; border-radius: 6px; padding: 7px 14px; font-weight: 600; cursor: pointer; font-size: 12px; margin-left: 8px; transition: background 0.15s ease; }
    .btn-bar button:hover { background: var(--accent-hover); }
    .badge { display: inline-block; padding: 4px 10px; border-radius: 9999px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
    .op-badge { background: #0369A1; color: #FFFFFF; font-size: 10px; padding: 2px 6px; }
    .group-badge { background: var(--badge-bg); color: var(--badge-text); border: 1px solid var(--badge-border); margin: 3px 4px 3px 0; text-transform: none; }
    .cards-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 16px; margin-bottom: 24px; }
    .panel-card { background: var(--bg-card); border: 1px solid var(--border-color); border-radius: 8px; padding: 18px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
    .panel-card h3 { margin-top: 0; margin-bottom: 14px; font-size: 14px; color: var(--accent); border-bottom: 1px solid var(--border-subtle); padding-bottom: 8px; }
    .field-row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid var(--border-subtle); font-size: 13px; }
    .field-label { color: var(--text-secondary); font-weight: 500; min-width: 130px; }
    .field-val { color: var(--text-primary); font-weight: 600; text-align: right; word-break: break-all; font-family: Consolas, monospace; }
    .section-title { font-size: 15px; font-weight: bold; color: var(--text-primary); margin: 26px 0 12px 0; display: flex; align-items: center; }
    .attr-table { width: 100%; border-collapse: collapse; background: var(--bg-card); border-radius: 8px; overflow: hidden; border: 1px solid var(--border-color); margin-top: 10px; }
    .attr-table th { background: var(--bg-card-header); color: var(--text-primary); text-align: left; padding: 10px 14px; font-size: 12px; text-transform: uppercase; }
    .attr-table td { padding: 8px 14px; border-bottom: 1px solid var(--border-subtle); font-size: 12px; }
    .attr-name { width: 220px; color: var(--accent); font-family: Consolas, monospace; }
    .attr-val { color: var(--text-secondary); word-break: break-all; font-family: Consolas, monospace; }
    .attr-type { width: 140px; color: var(--text-muted); }
    tr:hover { background: var(--table-row-hover); }
    .footer { text-align: center; margin-top: 32px; font-size: 12px; color: var(--text-muted); border-top: 1px solid var(--border-subtle); padding-top: 16px; }
    @media print {
        body { background-color: #FFFFFF !important; color: #000000 !important; padding: 0; }
        .btn-bar { display: none; }
        .panel-card, .attr-table { border: 1px solid #CCCCCC !important; background: #FAFAFA !important; color: #000000 !important; }
        .field-val, .field-label, .attr-table td, .attr-table th { color: #000000 !important; }
        .group-badge { background: #EEEEEE !important; color: #000000 !important; border: 1px solid #999999 !important; }
    }
</style>
</head>
<body>
<div class="container">
    <div class="top-bar">
        <div class="title-group">
            <div class="avatar-circle">$initials</div>
            <div>
                <h1>$([System.Net.WebUtility]::HtmlEncode($dispName))</h1>
                <p>Active Directory Object Report Card &bull; Template: $Template &bull; Generated $now</p>
            </div>
        </div>
        <div class="btn-bar">
            <span class="badge" style="background: $statusColor; color: #FFFFFF; margin-right: 12px;">$status</span>
            <button onclick="window.print()">&#x1F5B6;&#xFE0F; Print Dossier</button>
        </div>
    </div>

    $cardsGridHtml
    $groupsBlockHtml
    $attrBlockHtml

    <div class="footer">
        Active Directory Management Studio &bull; Enterprise Directory Services &amp; HTML Dossier Suite
    </div>
</div>
</body>
</html>
"@

    return $html
}

function Export-ADObjectToHtml {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        $ObjectDetail,

        [Parameter(Mandatory = $false)]
        [System.Collections.IEnumerable]$Attributes = @(),

        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [Parameter(Mandatory = $false)]
        [string]$Theme = "Dark",

        [Parameter(Mandatory = $false)]
        [string]$Template = "Technical",

        [Parameter(Mandatory = $false)]
        [string]$Title = ""
    )

    try {
        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $html = Get-ADObjectHtmlContent -ObjectDetail $ObjectDetail -Attributes $Attributes -Theme $Theme -Template $Template -Title $Title
        [System.IO.File]::WriteAllText($FilePath, $html, [System.Text.Encoding]::UTF8)

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Message  = "HTML Object Dossier generated successfully."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Message  = "Failed to generate HTML dossier: $_"
        }
    }
}

function Export-ADDataToDsml {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [System.Collections.IEnumerable]$Data,

        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [ValidateSet("searchResponse", "batchResponse", "batchRequest")]
        [string]$DocumentType = "batchResponse"
    )

    try {
        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $sb = New-Object System.Text.StringBuilder
        [void]$sb.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
        [void]$sb.AppendLine('<batchResponse xmlns="urn:oasis:names:tc:DSML:2:0:core">')
        [void]$sb.AppendLine('  <searchResponse>')

        $count = 0
        foreach ($item in $Data) {
            $dn = $item.DistinguishedName
            if (-not $dn -and $item.PSObject.Properties['DN']) { $dn = $item.DN }
            if (-not $dn -and $item.PSObject.Properties['distinguishedName']) { $dn = $item.distinguishedName }
            if (-not $dn) { continue }

            $escapedDn = [System.Security.SecurityElement]::Escape("$dn")
            [void]$sb.AppendLine("    <searchResultEntry dn=`"$escapedDn`">")

            foreach ($prop in $item.PSObject.Properties) {
                $name = $prop.Name
                $val = $prop.Value
                if ($name -match '^(DistinguishedName|DN|distinguishedName|RawValue|FlagList)$' -or $null -eq $val) {
                    continue
                }

                $escapedName = [System.Security.SecurityElement]::Escape("$name")
                [void]$sb.AppendLine("      <attr name=`"$escapedName`">")

                if ($val -is [System.Collections.IEnumerable] -and $val -isnot [string]) {
                    foreach ($subVal in $val) {
                        if ($subVal) {
                            $escapedVal = [System.Security.SecurityElement]::Escape("$subVal")
                            [void]$sb.AppendLine("        <value>$escapedVal</value>")
                        }
                    }
                }
                else {
                    $strVal = $val.ToString()
                    if ($strVal) {
                        $escapedVal = [System.Security.SecurityElement]::Escape("$strVal")
                        [void]$sb.AppendLine("        <value>$escapedVal</value>")
                    }
                }
                [void]$sb.AppendLine("      </attr>")
            }

            [void]$sb.AppendLine("    </searchResultEntry>")
            $count++
        }

        [void]$sb.AppendLine('    <searchResultDone>')
        [void]$sb.AppendLine('      <resultCode code="0" descr="success"/>')
        [void]$sb.AppendLine('    </searchResultDone>')
        [void]$sb.AppendLine('  </searchResponse>')
        [void]$sb.AppendLine('</batchResponse>')

        [System.IO.File]::WriteAllText($FilePath, $sb.ToString(), [System.Text.Encoding]::UTF8)

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = $count
            Message  = "DSML v2 XML export completed successfully ($count entries)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "DSML export failed: $_"
        }
    }
}

function Export-ADDataToScim {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [System.Collections.IEnumerable]$Data,

        [Parameter(Mandatory = $true)]
        [string]$FilePath
    )

    try {
        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $resources = [System.Collections.Generic.List[object]]::new()

        foreach ($item in $Data) {
            if (-not $item) { continue }

            # Detect if group or user
            $isGroup = $false
            if ($item.PSObject.Properties['GroupScope'] -or $item.ObjectClass -eq 'group' -or ($item.DistinguishedName -and $item.DistinguishedName -match '^CN=.*?,.*(Groups|OU=Groups)')) {
                $isGroup = $true
            } elseif ($item.PSObject.Properties['SamAccountName'] -and -not $item.PSObject.Properties['GivenName'] -and -not $item.PSObject.Properties['Surname'] -and -not $item.PSObject.Properties['UserPrincipalName']) {
                if ($item.PSObject.Properties['MemberCount'] -or $item.PSObject.Properties['Members']) {
                    $isGroup = $true
                }
            }

            $id = if ($item.ObjectGUID) { "$($item.ObjectGUID)" } elseif ($item.SID) { "$($item.SID)" } elseif ($item.SamAccountName) { "$($item.SamAccountName)" } else { [Guid]::NewGuid().ToString() }
            
            $createdIso = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssZ")
            if ($item.WhenCreated) {
                try {
                    $createdIso = ([DateTime]$item.WhenCreated).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
                } catch {
                    $createdIso = "$($item.WhenCreated)"
                }
            }

            $changedIso = $createdIso
            if ($item.WhenChanged) {
                try {
                    $changedIso = ([DateTime]$item.WhenChanged).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
                } catch {
                    $changedIso = "$($item.WhenChanged)"
                }
            }

            if ($isGroup) {
                # SCIM 2.0 Group Schema (RFC 7643 Section 4.2)
                $displayName = if ($item.DisplayName) { "$($item.DisplayName)" } elseif ($item.Name) { "$($item.Name)" } else { "$($item.SamAccountName)" }
                $grpObj = [ordered]@{
                    schemas      = @("urn:ietf:params:scim:schemas:core:2.0:Group")
                    id           = $id
                    displayName  = $displayName
                    externalId   = "$($item.DistinguishedName)"
                    meta         = [ordered]@{
                        resourceType = "Group"
                        created      = $createdIso
                        lastModified = $changedIso
                    }
                }

                if ($item.Members) {
                    $mList = [System.Collections.Generic.List[object]]::new()
                    foreach ($m in $item.Members) {
                        $mVal = if ($m.DistinguishedName) { $m.DistinguishedName } elseif ($m.SamAccountName) { $m.SamAccountName } else { "$m" }
                        $mDisplay = if ($m.DisplayName) { $m.DisplayName } elseif ($m.Name) { $m.Name } else { $mVal }
                        $mList.Add([ordered]@{
                            value   = $mVal
                            display = $mDisplay
                        })
                    }
                    $grpObj["members"] = $mList
                }

                $resources.Add($grpObj)
            }
            else {
                # SCIM 2.0 User Schema (RFC 7643 Section 4.1 & Enterprise Extension Section 4.3)
                $userName = if ($item.SamAccountName) { "$($item.SamAccountName)" } elseif ($item.UserPrincipalName) { "$($item.UserPrincipalName)" } else { "$($item.Name)" }
                $displayName = if ($item.DisplayName) { "$($item.DisplayName)" } elseif ($item.Name) { "$($item.Name)" } else { $userName }
                $givenName = if ($item.GivenName) { "$($item.GivenName)" } else { "" }
                $familyName = if ($item.Surname) { "$($item.Surname)" } elseif ($item.sn) { "$($item.sn)" } else { "" }

                $isActive = $true
                if ($null -ne $item.Enabled) {
                    $isActive = [bool]$item.Enabled
                } elseif ($item.Status -ieq "Disabled" -or $item.StatusBadge -ieq "Disabled") {
                    $isActive = $false
                }

                $userObj = [ordered]@{
                    schemas    = @(
                        "urn:ietf:params:scim:schemas:core:2.0:User",
                        "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
                    )
                    id         = $id
                    userName   = $userName
                    externalId = "$($item.DistinguishedName)"
                    name       = [ordered]@{
                        formatted  = $displayName
                        familyName = $familyName
                        givenName  = $givenName
                    }
                    displayName = $displayName
                    active     = $isActive
                }

                if ($item.Title) { $userObj["title"] = "$($item.Title)" }
                if ($item.Description) { $userObj["userType"] = "$($item.Description)" }

                # Emails
                $emailVal = if ($item.Mail) { "$($item.Mail)" } elseif ($item.Email) { "$($item.Email)" } elseif ($item.UserPrincipalName -match '@') { "$($item.UserPrincipalName)" } else { "" }
                if ($emailVal) {
                    $userObj["emails"] = @(
                        [ordered]@{
                            value   = $emailVal
                            type    = "work"
                            primary = $true
                        }
                    )
                }

                # Phone numbers
                $phones = [System.Collections.Generic.List[object]]::new()
                if ($item.telephoneNumber) {
                    $phones.Add([ordered]@{ value = "$($item.telephoneNumber)"; type = "work" })
                }
                if ($item.mobile) {
                    $phones.Add([ordered]@{ value = "$($item.mobile)"; type = "mobile" })
                }
                if ($phones.Count -gt 0) {
                    $userObj["phoneNumbers"] = $phones
                }

                # Addresses
                $addr = [ordered]@{}
                if ($item.streetAddress) { $addr["streetAddress"] = "$($item.streetAddress)" }
                if ($item.l -or $item.City) { $addr["locality"] = if ($item.l) { "$($item.l)" } else { "$($item.City)" } }
                if ($item.st -or $item.State) { $addr["region"] = if ($item.st) { "$($item.st)" } else { "$($item.State)" } }
                if ($item.postalCode -or $item.ZipCode) { $addr["postalCode"] = if ($item.postalCode) { "$($item.postalCode)" } else { "$($item.ZipCode)" } }
                if ($item.co -or $item.Country) { $addr["country"] = if ($item.co) { "$($item.co)" } else { "$($item.Country)" } }
                if ($addr.Count -gt 0) {
                    $addr["type"] = "work"
                    $userObj["addresses"] = @($addr)
                }

                # Meta
                $userObj["meta"] = [ordered]@{
                    resourceType = "User"
                    created      = $createdIso
                    lastModified = $changedIso
                }

                # Enterprise Extension (RFC 7643 Section 4.3)
                $enterpriseExt = [ordered]@{}
                if ($item.EmployeeID) { $enterpriseExt["employeeNumber"] = "$($item.EmployeeID)" }
                if ($item.Department) { $enterpriseExt["department"] = "$($item.Department)" }
                if ($item.Company) { $enterpriseExt["organization"] = "$($item.Company)" }
                if ($item.Division) { $enterpriseExt["division"] = "$($item.Division)" }
                if ($item.Manager) {
                    $mgrName = "$($item.Manager)"
                    if ($mgrName -match '^CN=([^,]+)') { $mgrDisp = $matches[1] } else { $mgrDisp = $mgrName }
                    $enterpriseExt["manager"] = [ordered]@{
                        value       = $mgrName
                        displayName = $mgrDisp
                    }
                }

                if ($enterpriseExt.Count -gt 0) {
                    $userObj["urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"] = $enterpriseExt
                }

                $resources.Add($userObj)
            }
        }

        # RFC 7644 Section 3.4.2 ListResponse
        $scimResponse = [ordered]@{
            schemas      = @("urn:ietf:params:scim:api:messages:2.0:ListResponse")
            totalResults = $resources.Count
            startIndex   = 1
            itemsPerPage = $resources.Count
            Resources    = $resources
        }

        $jsonStr = $scimResponse | ConvertTo-Json -Depth 10
        [System.IO.File]::WriteAllText($FilePath, $jsonStr, [System.Text.Encoding]::UTF8)

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = $resources.Count
            Message  = "SCIM 2.0 JSON export completed successfully ($($resources.Count) resources)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "SCIM 2.0 export failed: $_"
        }
    }
}

function New-LdifChangeScript {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        $OriginalObject,

        [Parameter(Mandatory = $true)]
        $ModifiedObject
    )

    $dn = if ($ModifiedObject.DistinguishedName) { $ModifiedObject.DistinguishedName } else { $OriginalObject.DistinguishedName }
    if (-not $dn) { return "# Error: Object must contain a DistinguishedName." }

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("dn: $dn")
    $lines.Add("changetype: modify")

    $props = @()
    if ($ModifiedObject.PSObject) {
        $props = $ModifiedObject.PSObject.Properties | Where-Object { $_.Name -notin @('DistinguishedName', 'ItemType', 'ObjectClass', 'IsOperational') } | Select-Object -ExpandProperty Name
    }

    $hasChanges = $false
    foreach ($p in $props) {
        $oldVal = if ($OriginalObject) { $OriginalObject.$p } else { $null }
        $newVal = $ModifiedObject.$p
        if ($oldVal -ne $newVal) {
            $hasChanges = $true
            if ($null -eq $newVal -or [string]::IsNullOrEmpty([string]$newVal)) {
                $lines.Add("delete: $p")
                $lines.Add("-")
            } else {
                $lines.Add("replace: $p")
                $lines.Add("$p`: $newVal")
                $lines.Add("-")
            }
        }
    }

    if (-not $hasChanges) {
        return "# No attribute differences detected.`ndn: $dn"
    }

    return ($lines -join "`r`n")
}

Export-ModuleMember -Function Export-ADDataToCsv, Export-ADDataToLdif, Export-ADDataToJson, Export-ADSecurityAuditToHtml, Export-ADObjectToHtml, Get-ADObjectHtmlContent, Export-ADDataToDsml, Export-ADDataToScim, New-LdifChangeScript


