<#
.SYNOPSIS
    ExportService module for Active Directory Management Studio.
.DESCRIPTION
    Provides CSV/Excel-compatible export capabilities with proper encoding, delimiter selection,
    and column mapping.
#>

function Export-ADDataToCsv {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [System.Collections.IEnumerable]$Data,

        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [string]$Delimiter = ";",

        [string[]]$PropertiesToExport = @()
    )

    try {
        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $exportList = if ($PropertiesToExport -and $PropertiesToExport.Count -gt 0) {
            $Data | Select-Object -Property $PropertiesToExport
        } else {
            $Data
        }

        # Export with UTF-8 encoding and specified delimiter
        $exportList | Export-Csv -Path $FilePath -Delimiter $Delimiter -NoTypeInformation -Encoding UTF8

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = @($exportList).Count
            Message  = "Export completed successfully ($(@($exportList).Count) records)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "Export failed: $_"
        }
    }
}

function Export-ADDataToLdif {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [System.Collections.IEnumerable]$Data,

        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [string]$ChangeType = "" # e.g. "add", "modify"
    )

    try {
        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $sb = New-Object System.Text.StringBuilder
        [void]$sb.AppendLine("version: 1")
        [void]$sb.AppendLine("# Generated by Active Directory Management Studio (LDIF Engine)")
        [void]$sb.AppendLine("# Export Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
        [void]$sb.AppendLine("")

        $count = 0
        foreach ($item in $Data) {
            $dn = $item.DistinguishedName
            if (-not $dn -and $item.PSObject.Properties['DN']) { $dn = $item.DN }
            if (-not $dn -and $item.PSObject.Properties['distinguishedName']) { $dn = $item.distinguishedName }
            if (-not $dn) { continue }

            [void]$sb.AppendLine("dn: $dn")
            if ($ChangeType) {
                [void]$sb.AppendLine("changetype: $ChangeType")
            }

            foreach ($prop in $item.PSObject.Properties) {
                $name = $prop.Name
                $val = $prop.Value
                if ($name -match '^(DistinguishedName|DN|distinguishedName|RawValue|FlagList)$' -or $null -eq $val) {
                    continue
                }

                if ($val -is [System.Collections.IEnumerable] -and $val -isnot [string]) {
                    foreach ($subVal in $val) {
                        if ($subVal) { [void]$sb.AppendLine("${name}: $subVal") }
                    }
                }
                else {
                    $strVal = $val.ToString()
                    if ($strVal) { [void]$sb.AppendLine("${name}: $strVal") }
                }
            }

            [void]$sb.AppendLine("")
            $count++
        }

        [System.IO.File]::WriteAllText($FilePath, $sb.ToString(), [System.Text.Encoding]::UTF8)

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = $count
            Message  = "LDIF export completed successfully ($count entries)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "LDIF export failed: $_"
        }
    }
}

function Export-ADDataToJson {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [System.Collections.IEnumerable]$Data,

        [Parameter(Mandatory = $true)]
        [string]$FilePath
    )

    try {
        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $json = $Data | ConvertTo-Json -Depth 5
        [System.IO.File]::WriteAllText($FilePath, $json, [System.Text.Encoding]::UTF8)

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = @($Data).Count
            Message  = "JSON export completed successfully ($(@($Data).Count) records)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "JSON export failed: $_"
        }
    }
}

function Export-ADSecurityAuditToHtml {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $false)]
        $AuditReport = $null,

        [Parameter(Mandatory = $false)]
        [string]$ReportTitle = "",

        [Parameter(Mandatory = $false)]
        [hashtable]$SummaryStats = @{},

        [Parameter(Mandatory = $false)]
        [System.Collections.IEnumerable]$Data = @(),

        [Parameter(Mandatory = $true)]
        [string]$FilePath
    )

    try {
        if ($AuditReport) {
            if (-not $ReportTitle) {
                $ReportTitle = if ($AuditReport.Title) { $AuditReport.Title } else { "Active Directory Security Audit Report" }
            }
            if ($AuditReport.SummaryStats -and -not $SummaryStats.Count) {
                $SummaryStats = [hashtable]$AuditReport.SummaryStats
            } elseif (-not $SummaryStats.Count) {
                $SummaryStats = [ordered]@{ "Total Findings" = $AuditReport.Count; "Category" = $AuditReport.Category }
            }
            if (-not $Data -or $Data.Count -eq 0) {
                $Data = if ($AuditReport.Findings) { $AuditReport.Findings } else { $AuditReport.Results }
            }
        }

        $targetDir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($targetDir -and -not (Test-Path $targetDir)) {
            [void](New-Item -ItemType Directory -Path $targetDir -Force)
        }

        $now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

        $cardsHtml = ""
        foreach ($k in $SummaryStats.Keys) {
            $val = $SummaryStats[$k]
            $cardsHtml += @"
            <div class="card">
                <div class="card-val">$val</div>
                <div class="card-label">$k</div>
            </div>
"@
        }

        # Convert data items to HTML table rows
        $first = $Data | Select-Object -First 1
        $headers = if ($first) { $first.PSObject.Properties.Name } else { @() }
        
        $thHtml = ($headers | ForEach-Object { "<th>$_</th>" }) -join ""
        $trHtml = ""

        foreach ($row in $Data) {
            $tds = foreach ($h in $headers) {
                $v = $row.$h
                "<td>$([System.Web.HttpUtility]::HtmlEncode("$v"))</td>"
            }
            $trHtml += "<tr>$($tds -join '')</tr>`n"
        }

        $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>$ReportTitle - Active Directory Management Studio</title>
<style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0F1117; color: #E1E7EF; margin: 0; padding: 24px; }
    .header { border-bottom: 2px solid #2A2E3D; padding-bottom: 16px; margin-bottom: 24px; }
    .title { font-size: 24px; font-weight: bold; color: #60A5FA; margin: 0 0 6px 0; }
    .meta { font-size: 13px; color: #94A3B8; }
    .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 28px; }
    .card { background: #1A1D27; border: 1px solid #2D3345; border-radius: 8px; padding: 16px; text-align: center; }
    .card-val { font-size: 28px; font-weight: bold; color: #38BDF8; }
    .card-label { font-size: 12px; color: #94A3B8; text-transform: uppercase; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; background: #161821; border-radius: 8px; overflow: hidden; border: 1px solid #2A2E3D; }
    th { background: #1E2230; color: #F1F5F9; font-weight: 600; text-align: left; padding: 12px 14px; font-size: 13px; border-bottom: 1px solid #2A2E3D; }
    td { padding: 10px 14px; border-bottom: 1px solid #232736; font-size: 13px; color: #CBD5E1; }
    tr:hover { background: #1C202C; }
    .footer { margin-top: 28px; font-size: 12px; color: #64748B; text-align: center; }
</style>
</head>
<body>
    <div class="header">
        <div class="title">&#x1F6E1;&#xFE0F; $ReportTitle</div>
        <div class="meta">Generated: $now | Source: Active Directory Management Studio</div>
    </div>

    <div class="cards">
        $cardsHtml
    </div>

    <table>
        <thead>
            <tr>$thHtml</tr>
        </thead>
        <tbody>
            $trHtml
        </tbody>
    </table>

    <div class="footer">
        Active Directory Management Studio &bull; Enterprise Directory Services & Audit Suite
    </div>
</body>
</html>
"@

        [System.IO.File]::WriteAllText($FilePath, $html, [System.Text.Encoding]::UTF8)

        return [PSCustomObject]@{
            Success  = $true
            FilePath = $FilePath
            Count    = @($Data).Count
            Message  = "HTML Report generated successfully ($(@($Data).Count) records)."
        }
    }
    catch {
        return [PSCustomObject]@{
            Success  = $false
            FilePath = $FilePath
            Count    = 0
            Message  = "HTML Report generation failed: $_"
        }
    }
}

Export-ModuleMember -Function Export-ADDataToCsv, Export-ADDataToLdif, Export-ADDataToJson, Export-ADSecurityAuditToHtml

